[build]
  command = "hugo --logLevel info"
  publish = "public"

[build.environment]
  # Use a recent version that satisfies the theme's minimum (>= 0.128)
  HUGO_VERSION = "0.129.0"
  # Force the extended binary (enables SCSS/Sass pipeline)
  HUGO_EXTENDED = "true"
